version: "3.3"

services:
  server-udp:
    build:
      context: ipkpd
      dockerfile: Dockerfile
    environment:
        PORT: 3023
        HOST: 127.0.0.1
        MODE: udp
    container_name: ipk-server-udp
    ports:
      - "3023:3023"
    volumes:
      - ./src:/ipk/project1/src
    restart: always

  server-tcp:
    build:
      context: ipkpd
      dockerfile: Dockerfile
    environment:
        PORT: 2023
        HOST: 127.0.0.1
        MODE: tcp
    container_name: ipk-server-tcp
    ports:
      - "2023:3023"
    volumes:
      - ./src:/ipk/project1/src
    restart: always
