all:
	(cd DemoBlock && make)
	(cd DemoFork && make)
	(cd DemoMessenger && make)
	(cd DemoNonBlock && make)
	(cd DemoSelect && make)
	(cd DemoTcp && make)
	(cd DemoUdp && make)
	(cd SimpleIPv6 && make)
